### ISSUE TITLE
Add new design for Add Anime screen

### ISSUE THREAD

**Issue by MaisaMilena** [MaisaMilena/MyAnimeList#16]
## Description
Implement new design for AddAnime screen. Related to Issue #5 
Follow [Screen Design](https://projects.invisionapp.com/share/AROFZLETWGU#/screens) 
### You will need to:
- Work on the storyboard AddAnime.storyboard
- Use the colors (PrimaryBlue and SecondaryGray) available on InterfaceBuilder
- If need to use colors in code, use the colors available as an extension of UIColor (UIColor.primaryBlue and UIColor.secondaryGray)

## Criteria of acceptance:
- [ ] Follow the spacing and elements of the prototype screen
- [ ] Only work on the AddAnime.storyboard
- [ ] Apply the fonts described in the prototype
- [ ] Apply the colors described in the prototype
- [ ] Be careful with constraints 
- [ ] The screen has to continue to check if Title and Description are empty. 
- [ ] Field Rating has to be changed to be an input. It cannot be empty, must receive values between 1 to 5

**Comment by MaisaMilena** [comment]
@jayahariv can you do it?

**Comment by FraDeliro** [comment]
Hi @MaisaMilena, if you agree I can pick up this one :) and I would also open two more issues related with Swift 5 conversion and MyAnimeList new design screen. I could work on all of them. Let me know, thanks!

**Comment by MaisaMilena** [comment]
sorry for the delay in reply =(
if you are still interested, go for it! xD

**Comment by FraDeliro** [comment]
Thanks :), I opened a PR.

**Comment by MaisaMilena** [comment]
thank you for your contribution!
