### ISSUE TITLE
Update rating score from a boring UISlider to Stars

### ISSUE THREAD

**Issue by MaisaMilena** [MaisaMilena/MyAnimeList#4]
## Description
Currently, the rating score is a very simples UISlider, it's not good.
Let's do it with starts like this one:
<img width="253" alt="image" src="https://user-images.githubusercontent.com/28612369/46386381-95c6df80-c697-11e8-9e33-4a041e3b9844.png">
**Tip**: there are some tutorials and frameworks available to help you implement it.  
## Criteria of acceptance
- Do a star rating score. You decide how to do it:
   - it can be simple: a collection of buttons with tag from 1 to 5. When a button is clicked, identify it's tag and that's the score.
   - use a framework were the slide fills the stars

**Comment by jayahariv** [comment]
@MaisaMilena  I can take this up! and submit the pull request. #hackthoberfest
