### ISSUE TITLE
New design for iOS screen

### ISSUE THREAD

**Issue by MaisaMilena** [MaisaMilena/MyAnimeList#5]
## Description
The current screens of the app were designed by... well... a programmer.
It's functional but not beautiful, we can do it better.  

**Screen of Add Anime:**
<img width="314" alt="image" src="https://user-images.githubusercontent.com/28612369/46386654-1a662d80-c699-11e8-9eed-9d9353db9c1f.png">

## Criteria of acceptance
- Do a new design for the Home Screen 
- Do a new design for the screen of Add Anime
- A link of the design prototype must be available on InVision app or similar. It has to contain the colors used, spacing, font type and size. If some image or icon is used, add it references on the file "License - Use of image"

**Comment by jayahariv** [comment]
Can you share the UI spec and more details? if I get some time I can try doing this

**Comment by MaisaMilena** [comment]
First, we need a new design prototype (available on InVision).  There are no specifications, just to be more beautiful than actually is hahaha
Then, in another issue, do the implementation of the design following the criteria of the template

@jayahariv are you a developer, right?
1- I can find a designer to do the design and then I call you to do the implementation
2- If you can do a better view without a designer, go ahead! hahaha (KeralaRescueiOS is a beautiful app 😄)

**Comment by jayahariv** [comment]
If you can find a designer, that would be great. I am a developer. Let me know when the design is ready.

Thanks, @MaisaMilena, KeralaRescueiOS was a quick application for the awareness of Flood in our state.
